//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace MathNet.Numerics.Properties {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
#if NET45REFLECTION
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Numerics.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
#else
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Numerics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
#endif
                return resourceMan;
            }
        }

        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The accuracy couldn&apos;t be reached with the specified number of iterations. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccuracyNotReached {
            get {
                return ResourceManager.GetString("AccuracyNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The array arguments must have the same length. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentArraysSameLength {
            get {
                return ResourceManager.GetString("ArgumentArraysSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given array is the wrong length. Should be {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentArrayWrongLength {
            get {
                return ResourceManager.GetString("ArgumentArrayWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The argument must be between 0 and 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentBetween0And1 {
            get {
                return ResourceManager.GetString("ArgumentBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value cannot be in the range -1 &lt; x &lt; 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentCannotBeBetweenOneAndNegativeOne {
            get {
                return ResourceManager.GetString("ArgumentCannotBeBetweenOneAndNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be even. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentEven {
            get {
                return ResourceManager.GetString("ArgumentEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The histogram does not contain the value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentHistogramContainsNot {
            get {
                return ResourceManager.GetString("ArgumentHistogramContainsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is expected to be between {0} and {1} (including {0} and {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentInIntervalXYInclusive {
            get {
                return ResourceManager.GetString("ArgumentInIntervalXYInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one item of {0} is a null reference (Nothing in Visual Basic). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentItemNull {
            get {
                return ResourceManager.GetString("ArgumentItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be greater than or equal to one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentLessThanOne {
            get {
                return ResourceManager.GetString("ArgumentLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree..
        /// </summary>
        public static string ArgumentMatrixDimensions {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix dimensions must agree: {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixDimensions1 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix dimensions must agree: op1 is {0}, op2 is {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixDimensions2 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix dimensions must agree: op1 is {0}, op2 is {1}, op3 is {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixDimensions3 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The requested matrix does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentMatrixDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The matrix indices must not be out of range of the given matrix. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentMatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must not be rank deficient. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixNotRankDeficient {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotRankDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must not be singular. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixNotSingular {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must be positive definite. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix column dimensions must agree. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSameColumnDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameColumnDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix row dimensions must agree. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSameRowDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameRowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must have exactly one column. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSingleColumn {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must have exactly one column and row, thus have only one cell. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSingleColumnRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must have exactly one row. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSingleRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must be square. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSquare {
            get {
                return ResourceManager.GetString("ArgumentMatrixSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must be symmetric. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSymmetric {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matrix must be symmetric positive definite. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMatrixSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In the specified range, the minimum is greater than maximum. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("ArgumentMinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be positive. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must neither be infinite nor NaN. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentNotInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentNotInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must not be negative (zero is ok). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is a null reference (Nothing in Visual Basic). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be odd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentOdd {
            get {
                return ResourceManager.GetString("ArgumentOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be greater than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be greater than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentOutOfRangeGreaterEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller than {1}..
        /// </summary>
        public static string ArgumentOutOfRangeSmaller {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeSmaller", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller than or equal to {1}..
        /// </summary>
        public static string ArgumentOutOfRangeSmallerEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeSmallerEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The chosen parameter set is invalid (probably some value is out of range)..
        /// </summary>
        public static string ArgumentParameterSetInvalid {
            get {
                return ResourceManager.GetString("ArgumentParameterSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given expression does not represent a complex number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentParseComplexNumber {
            get {
                return ResourceManager.GetString("ArgumentParseComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be positive (and not zero). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size must be a Power of Two. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size must be a Power of Two in every dimension. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentPowerOfTwoEveryDimension {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwoEveryDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The range between {0} and {1} must be less than or equal to {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments must be different objects. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentReferenceDifferent {
            get {
                return ResourceManager.GetString("ArgumentReferenceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Array must have exactly one dimension (and not be null). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentSingleDimensionArray {
            get {
                return ResourceManager.GetString("ArgumentSingleDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentTooLarge {
            get {
                return ResourceManager.GetString("ArgumentTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too large for the current iteration limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentTooLargeForIterationLimit {
            get {
                return ResourceManager.GetString("ArgumentTooLargeForIterationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type mismatch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be strictly larger than the lower bound..
        /// </summary>
        public static string ArgumentUpperBoundMustBeLargerThanLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be at least as large as the lower bound..
        /// </summary>
        public static string ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length must be a multiple of {0}..
        /// </summary>
        public static string ArgumentVectorLengthsMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentVectorLengthsMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All vectors must have the same dimensionality. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentVectorsSameLength {
            get {
                return ResourceManager.GetString("ArgumentVectorsSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The vector must have 3 dimensions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentVectorThreeDimensional {
            get {
                return ResourceManager.GetString("ArgumentVectorThreeDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given array is too small. It must be at least {0} long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Big endian files are not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BigEndianNotSupported {
            get {
                return ResourceManager.GetString("BigEndianNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The supplied collection is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complex matrices are not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComplexMatricesNotSupported {
            get {
                return ResourceManager.GetString("ComplexMatricesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An algorithm failed to converge. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvergenceFailed {
            get {
                return ResourceManager.GetString("ConvergenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is not implemented yet (but is planned). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeaturePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("FeaturePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given file doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample points should be sorted in strictly ascending order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotStrictlyAscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All sample points should be unique. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Interpolation_Initialize_SamplePointsNotUnique {
            get {
                return ResourceManager.GetString("Interpolation_Initialize_SamplePointsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameterization for the distribution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDistributionParameters {
            get {
                return ResourceManager.GetString("InvalidDistributionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Left Boundary Condition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidLeftBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidLeftBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation could not be performed because the accumulator is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationAccumulatorEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationAccumulatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation could not be performed because the histogram is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationHistogramEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not enough points in the distribution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationHistogramNotEnoughPoints {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Samples Provided. Preparation Required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationNoSamplesProvided {
            get {
                return ResourceManager.GetString("InvalidOperationNoSamplesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was passed to a native method..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was passed to a native method, parameter number : {0}.
        /// </summary>
        public static string InvalidParameterWithNumber {
            get {
                return ResourceManager.GetString("InvalidParameterWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Right Boundary Condition..
        /// </summary>
        public static string InvalidRightBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidRightBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag must be positive.
        /// </summary>
        public static string LagMustBePositive {
            get {
                return ResourceManager.GetString("LagMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag must be smaller than the sample size.
        /// </summary>
        public static string LagMustBeSmallerThanTheSampleSize {
            get {
                return ResourceManager.GetString("LagMustBeSmallerThanTheSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss yyyy.
        /// </summary>
        public static string MatlabDateHeaderFormat {
            get {
                return ResourceManager.GetString("MatlabDateHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices can not be empty and must have at least one row and column..
        /// </summary>
        public static string MatrixCanNotBeEmpty {
            get {
                return ResourceManager.GetString("MatrixCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns of a matrix must be positive..
        /// </summary>
        public static string MatrixColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be in sparse storage format.
        /// </summary>
        public static string MatrixMustBeSparse {
            get {
                return ResourceManager.GetString("MatrixMustBeSparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows of a matrix must be positive..
        /// </summary>
        public static string MatrixRowsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of rows or columns of a matrix must be positive. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatrixRowsOrColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsOrColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to allocate native memory..
        /// </summary>
        public static string MemoryAllocation {
            get {
                return ResourceManager.GetString("MemoryAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 and 2 dimensional arrays are supported..
        /// </summary>
        public static string MoreThan2D {
            get {
                return ResourceManager.GetString("MoreThan2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data must contain at least {0} values. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MustContainAtLeast {
            get {
                return ResourceManager.GetString("MustContainAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name cannot contain a space. name:  {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameCannotContainASpace {
            get {
                return ResourceManager.GetString("NameCannotContainASpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a supported type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm experience a numerical break down
        ///.
        /// </summary>
        public static string NumericalBreakdown {
            get {
                return ResourceManager.GetString("NumericalBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two arguments can&apos;t be compared (maybe they are part of a partial ordering?).
        /// </summary>
        public static string PartialOrderException {
            get {
                return ResourceManager.GetString("PartialOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The integer array does not represent a valid permutation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PermutationAsIntArrayInvalid {
            get {
                return ResourceManager.GetString("PermutationAsIntArrayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sampler&apos;s proposal distribution is not upper bounding the target density. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProposalDistributionNoUpperBound {
            get {
                return ResourceManager.GetString("ProposalDistributionNoUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RootFindingFailed {
            get {
                return ResourceManager.GetString("RootFindingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds. Consider to use RobustNewtonRaphson instead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RootFindingFailedRecommendRobustNewtonRaphson {
            get {
                return ResourceManager.GetString("RootFindingFailedRecommendRobustNewtonRaphson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The lower and upper bounds must bracket a single root. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RootMustBeBracketedByBounds {
            get {
                return ResourceManager.GetString("RootMustBeBracketedByBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The algorithm ended without root in the range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RootNotFound {
            get {
                return ResourceManager.GetString("RootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of rows must greater than or equal to the number of columns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RowsLessThanColumns {
            get {
                return ResourceManager.GetString("RowsLessThanColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U is singular, and the inversion could not be completed..
        /// </summary>
        public static string SingularUMatrix {
            get {
                return ResourceManager.GetString("SingularUMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U is singular, and the inversion could not be completed. The {0}-th diagonal element of the factor U is zero..
        /// </summary>
        public static string SingularUMatrixWithElement {
            get {
                return ResourceManager.GetString("SingularUMatrixWithElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The singular vectors were not computed..
        /// </summary>
        public static string SingularVectorsNotComputed {
            get {
                return ResourceManager.GetString("SingularVectorsNotComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This special case is not supported yet (but is planned). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialCasePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("SpecialCasePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given stop criterion already exist in the collection..
        /// </summary>
        public static string StopCriterionDuplicate {
            get {
                return ResourceManager.GetString("StopCriterionDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no stop criterion in the collection..
        /// </summary>
        public static string StopCriterionMissing {
            get {
                return ResourceManager.GetString("StopCriterionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String parameter cannot be empty or null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We only support sparse matrix with less than int.MaxValue elements. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooManyElements {
            get {
                return ResourceManager.GetString("TooManyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The moment of the distribution is undefined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedMoment {
            get {
                return ResourceManager.GetString("UndefinedMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A user defined provider has not been specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDefinedProviderNotSpecified {
            get {
                return ResourceManager.GetString("UserDefinedProviderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User work buffers are not supported by this provider..
        /// </summary>
        public static string UserWorkBufferNotSupported {
            get {
                return ResourceManager.GetString("UserWorkBufferNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors can not be empty and must have at least one element..
        /// </summary>
        public static string VectorCanNotBeEmpty {
            get {
                return ResourceManager.GetString("VectorCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given work array is too small. Check work[0] for the corret size..
        /// </summary>
        public static string WorkArrayTooSmall {
            get {
                return ResourceManager.GetString("WorkArrayTooSmall", resourceCulture);
            }
        }
    }
}
